---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ibot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ibot
  filterTags:
    pattern: '.*-dev.*'
  policy:
    semver:
      range: '^1.x-0'